-- Supabase Tabloları Oluşturma SQL Komutları

-- 1. Psikologlar Tablosu
CREATE TABLE psychologists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  renk_kodu TEXT
);

-- 2. Danışanlar Tablosu
CREATE TABLE clients (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  registration_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  psychologist_id INTEGER REFERENCES psychologists(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Randevular Tablosu
create table if not exists appointments (
  id serial primary key,
  client_id integer references clients(id) on delete set null,
  psychologist_id integer references psychologists(id) on delete set null,
  appointment_date timestamp not null,
  hour integer not null,
  minute integer not null,
  duration integer not null,
  description text,
  fee integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Notlar Tablosu
CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  psychologist_id INTEGER NOT NULL REFERENCES psychologists(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- `giderler` tablosu
create table public.giderler (
  id bigint generated by default as identity,
  tarih date null,
  aciklama text null,
  tutar numeric null,
  odeme_yontemi text null,
  kategori text null,
  is_transfer boolean null default false,
  transfer_id text null,
  constraint giderler_pkey primary key (id)
);

-- `gelirler` tablosu
create table public.gelirler (
  id bigint generated by default as identity,
  tarih date null,
  aciklama text null,
  kategori text null,
  tutar numeric null,
  odeme_yontemi text null,
  is_transfer boolean null default false,
  transfer_id text null,
  constraint gelirler_pkey primary key (id)
);